spring:
  application:
    name: agarang

---
spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret, server-common
      green: green, common, secret, server-common

server:
  env: blue

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8080

serverAddress: localhost
serverName: local_server

aws:
  s3:
    upload:
      tmpPath: ./s3-uploads/

---
spring:
  config:
    activate:
      on-profile: blue

server:
  port: 8080

serverName: blue_server

---
spring:
  config:
    activate:
      on-profile: green

server:
  port: 8081

serverName: green_server

---
spring:
  config:
    activate:
      on-profile: server-common

serverAddress: 43.200.109.115

aws:
  s3:
    upload:
      tmpPath: /var/app/s3-uploads/

---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
  servlet:
    multipart: # TODO: Exception Handler 추가하기
      max-file-size: 5MB
      max-request-size: 10MB

---
spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

---
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3d383048d0b0826ac21859d18c890bf3
            client-secret: qDrs3hBTyP5NeR4hED5i9gUQyrTrl5oY
            redirect-uri: "${baseUrl}/oauth2/callback/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

baseUrl: http://localhost:8080
---
secret:
  jwt-secret-key: 12sdfa3sDGA246dfhsfjghjddFJ2612adfsaSGADS3ddfsdfsfdsfdsfdsfeadfwerghrtwherthetyjtyjruyjkxuyk # 임시, 환경변수로
  jwt-expired-in: 3600000  # 1시간